---
- name: Deploy Imgproxy and Caddy with Docker Compose and systemd
  hosts: webservers
  become: true
  gather_facts: true
  vars_files:
    - global_variables.yml
  roles:
    - wait_for_connection
    - packages
    # - journalctl # careful, we reduced log size and duration
    - imgproxy
    - security
    - geerlingguy.swap
