---
- name: Base server
  hosts: packer-base
  become: true
  gather_facts: true
  vars_files:
    - global_variables.yml
  roles:
    - wait_for_connection
    - packages
    # - journalctl # careful, we reduced log size and duration
    # - firewall # no need, since we're using firewall from providers
    - security
    - geerlingguy.swap
