---
- name: Configure ufw defaults for incoming traffic
  community.general.ufw:
    default: deny
    direction: incoming

- name: Configure ufw defaults for outgoing traffic
  community.general.ufw:
    default: allow
    direction: outgoing

- name: Configure ufw rules
  community.general.ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop:
    - rule: 'limit'
      port: '22'
      proto: 'tcp'
    - rule: 'allow'
      port: '80'
      proto: 'tcp'
    - rule: 'allow'
      port: '443'
      proto: 'tcp'

- name: Enable ufw
  community.general.ufw:
    state: enabled
