---
- name: Base server
  hosts: packer-base
  become: true
  gather_facts: true
  vars_files:
    - global_variables.yml
  roles:
    - wait_for_connection
    - packages
    - security
    - geerlingguy.swap
